name: First Workflow

on: push

jobs:
  first_job:
    name: First Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: List and read files
        run: |
          echo "First GitHub Actions job"
          ls -ltra
          cat README.md

      - name: Generate ASCII artwork
        run: cowsay -f dragon "Run for cover, I am a DRAGON... RAWR" >> dragon.txt

      # - name: List files
      #   run: ls

      # - name: Read file
      #   run: cat README.md
