## Variables can be defined at the step, job, or workflow level
## Variables defined in the workflow can be used with ${{ env.VARIABLE_NAME }} or $VARIABLE_NAME
## Variables defined in the repo can be used with ${{ vars.VARIABLE_NAME }}
## Secrets defined in the repo and can be called with ${{ secrets.SECRET_NAME }}
name: Variables and Secrets

on:
  workflow_dispatch:
  # schedule can be delayed, see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  # schedule:
  #   - cron: '*/1 * * * *'
  # push

env:
  CONTAINER_REGISTRY: docker.io
  IMAGE_NAME: github-actions-nginx

jobs:
  docker:
    name: Docker Job
    runs-on: ubuntu-latest
    steps:
      - name: Docker build
        run: echo docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

      - name: Docker login
        run: echo docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

      - name: Docker publish
        run: echo docker push ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

  deploy:
    needs: docker
    name: Deploy Job
    runs-on: ubuntu-latest
    concurrency:
      group: production-deployment
      cancel-in-progress: true
    steps:
      - name: Docker run
        run: |
          echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest
          sleep 60s