## Variables can be defined at the step, job, or workflow level
## Variables (defined in the workflow or in the repo) can be called with 
## ${{ env.VARIABLE_NAME }} or $VARIABLE_NAME
## Secrets are defined in the repo and can be called with ${{ secrets.SECRET_NAME }}
name: Variables and Secrets

on:
  push

env:
  CONTAINER_REGISTRY: docker.io
  IMAGE_NAME: github-actions-nginx

jobs:
  docker:
    name: Docker Job
    runs-on: ubuntu-latest
    steps:
      - name: Docker build
        run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

      - name: Docker login
        run: echo docker login --username=$DOCKER_USERNAME --password=${{ secrets.DOCKER_PASSWORD }}

      - name: Docker publish
        run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

  deploy:
    needs: docker
    name: Deploy Job
    runs-on: ubuntu-latest
    steps:
      - name: Docker run
        run:  echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest