## Variables can be defined at the step, job, or workflow level
## Variables can be called with ${{ env.VARIABLE_NAME }} or $VARIABLE_NAME
name: Variables and Secrets

on:
  push

env:
  CONTAINER_REGISTRY: docker.io
  DOCKER_USERNAME: lancehampton
  IMAGE_NAME: github-actions-nginx

jobs:
  docker:
    name: Docker Job
    runs-on: ubuntu-latest
    steps:
      - name: Docker build
        run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

      - name: Docker login
        env:
          DOCKER_PASSWORD: s3cUr3P@ssw0rd
        run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

      - name: Docker publish
        run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

  deploy:
    needs: docker
    name: Deploy Job
    runs-on: ubuntu-latest
    steps:
      - name: Docker run
        run:  docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest